### ISSUE TITLE
CMU Phoneme-to-viseme mappings

### ISSUE THREAD

**Issue by GeorgeS2019** [kaiidams/voice100#48]
Do you have plan to evaluate the [39 CMU Phoneme](http://www.speech.cs.cmu.edu/cgi-bin/cmudict)-to-viseme mappings?

**Comment by kaiidams** [comment]
If you just want to do voice100-runtime, then https://github.com/Kyubyong/g2p is used to translate English to phonemes.
In case of C#, we need C# implementation of English to phonemes, or the model needs to be modified like English->phonems,audio.
